name: model-training
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: train time series model
        run: |
          pip install -r requirements.txt
          python scripts/random_forest.py
      - name: Write CML report
        run: |
          # Post reports as comments in GitHub PRs
          # LSTM
          cd img/
          echo "## Model Training Completed" > report.md
          echo "### Sales Model" >> report.md
          echo "### Model training history" >> report.md
          cml-publish LSTM.png --md >> report.md
          cml send-comment report.md
